
GET http://localhost:3333/

###

// Documentation
GET http://localhost:3333/docs

###

// Auth
POST http://localhost:3333/api/auth/register
Content-Type: application/json

{
  "name": "[Username]",
  "email": "[EMAIL_ADDRESS]",
  "password": "[PASSWORD]",
  "confirmPassword": "[PASSWORD]"
}

###

POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
  "email": "[EMAIL_ADDRESS]",
  "password": "[PASSWORD]"
}

###